### ISSUE TITLE
Error handling not working

### ISSUE THREAD

**Issue by abhijeethallur** [ZahraHeydari/Android-Clean-Arch-Coroutines-Koin#5]
When an API exception is happening the exception should be caught in catch block is it?

`
fun invoke(
        scope: CoroutineScope,
        params: Params?,
        onResult: (UseCaseResponse<Type>)
    ) {
        val backgroundJob = scope.async {
            run(params)
        }
        scope.launch {
            backgroundJob.await().let {
                try {
                    Log.e("UseCase", "Success")
                    onResult.onSuccess(it)
                } catch (e: Exception) {
                    Log.e("UseCase", "Exception")
                    onResult.onError(apiErrorHandle?.traceErrorException(e))
                }
            }
        }
    }
`

But this is not happening. Am I missing anything?

**Comment by ZahraHeydari** [comment]
I found a new solution to handle it! You can use it and please let me know if it still doesn`t work.

`  @ExperimentalCoroutinesApi
    fun invoke(
        scope: CoroutineScope,
        params: Params?,
        onResult: (UseCaseResponse<Type>)
    ) {
        val backgroundJob = scope.async { run(params) }
        scope.launch {
            backgroundJob.await().let {
                backgroundJob.invokeOnCompletion {
                    if (backgroundJob.isCompleted) {
                        onResult.onSuccess(backgroundJob.getCompleted())
                    } else {
                        onResult.onError(apiErrorHandle?.traceErrorException(it))
                    }
                }
            }
        }
    }
`

**Comment by hectorhalpizar** [comment]
I tried your solution and it didn't worked for me. This happens when the request failed with other responses like 401 or 403.

I did this patch on Android Studio 3.6.1. 

But I feel it messes with the Clean Architecture concept. Maybe it will give you an idea of what is happening.

[Fix_crash_when_request_fails.patch.txt](https://github.com/ZahraHeydari/Android-Clean-Arch-Coroutines-Koin/files/4302743/Fix_crash_when_request_fails.patch.txt)

**Comment by ZahraHeydari** [comment]
Another solution which I used:
`
 @ExperimentalCoroutinesApi
    fun invoke(
            params: Params?,
            onResult: (UseCaseResponse<Type>)?
    ) {
        CoroutineScope(Dispatchers.Main).launch {
            try {
                val result = run(params)
                onResult?.onSuccess(result)
                Log.d(TAG, "Response: $result")
            } catch (e: CancellationException) {
                Log.d(TAG, "Error: $e")
                onResult?.onError(apiErrorHandle.traceErrorException(e))
            } catch (e: Exception) {
                Log.d(TAG, "Error: $e cause: ${e.cause}")
                onResult?.onError(apiErrorHandle.traceErrorException(e))
            }
        }
    }
`
