### ISSUE TITLE
Can use cases contain models from the data package?

### ISSUE THREAD

**Issue by ThanosFisherman** [ZahraHeydari/Android-Clean-Arch-Coroutines-Koin#7]
Hi Zara, thanks for the nice sample. I do have one question.

Can [GetPostsUseCase](https://github.com/ZahraHeydari/Android-Clean-Arch-Coroutines-Koin/blob/master/app/src/main/java/com/android/post/domain/usecase/GetPostsUseCase.kt) contain `Post` and `ApiErrorHandle` from the data package? I thought that something like that was prohibited by clean architecture principles as domain should not depend on anything else.

Is there maybe an exception for this case?

Regards,
Thanos

**Comment by ZahraHeydari** [comment]
Hi Thanos,

Thank you for mentioning this mistake. you are absolutely right. It`s obvious the domain layer should not depend on the data layer. I`ll fix this issue.

**Comment by ZahraHeydari** [comment]
Hi Thanos,

Thank you for mentioning this mistake. you are absolutely right. It is obvious the domain layer should not depend on the data layer. I will fix this issue.

**Comment by ThanosFisherman** [comment]
Thanks for clarifying this. 👍 I Hope my message finds you in good health. You may close this issue if you feel like so.
